Repository whotracksme/webextension-packages, pull requests merged in 2022-12, with the labels that each got.

#37 Backport 0.4 changes
  packages/trackers-preview/src/content_scripts/index.js
  packages/trackers-preview/src/content_scripts/styles.css
  packages/trackers-preview/src/page_scripts/index.js
Labels: minor

#38 Adds functional tests and fix problems found
  package-lock.json
  packages/reporting/karma.conf.cjs
  packages/reporting/package.json
  packages/reporting/src/patterns.js
  packages/reporting/src/sanitizer.js
  packages/reporting/src/search-extractor.js
  packages/reporting/test/helpers/dom-parsers.js
  packages/reporting/test/index.js
  packages/reporting/test/patterns.spec.js
  packages/reporting/test/sanitizer.spec.js
  packages/reporting/test/search-extractor.spec.js
  packages/reporting/test/url-analyzer.spec.js
Labels: bug

#40 Trackers Preview: fix import of pre-generated data
  packages/trackers-preview/src/background/index.js
Labels: patch
