Repository whotracksme/webextension-packages, pull requests merged in 2024-10, with the labels that each got.

#97 Preserve "openedFrom" information during redirects opening in new tabs
  reporting/karma.conf.cjs
  reporting/src/pages.js
  reporting/test/pages.spec.js
Labels: bug

#104 PageStore cleanup
  reporting/src/webrequest-pipeline/page-store.js
  reporting/test/helpers/scenarios.js
  reporting/test/request-reporter.test.js
  reporting/test/request/index.spec.js
  reporting/test/webrequest-pipeline/index.test.js
  reporting/test/webrequest-pipeline/page-store.test.js
Labels: internal

#105 PageStore cleanup
  reporting/src/request/steps/page-logger.js
  reporting/src/webrequest-pipeline/page-store.js
  reporting/src/webrequest-pipeline/page.js
  reporting/src/webrequest-pipeline/webrequest-context.js
  reporting/test/request/index.spec.js
  reporting/test/webrequest-pipeline/page-store.test.js
Labels: internal

#106 webrequest-pipeline cleanup
  reporting/example/index.js
  reporting/example/manifests/chromium.json
  reporting/src/request/dnt.js
  reporting/src/request/index.js
  reporting/src/request/page-telemetry.js
  reporting/src/request/steps/page-logger.js
  reporting/src/webrequest-pipeline/page-store.js
  reporting/src/webrequest-pipeline/webrequest-context.js
  reporting/test/request/index.spec.js
Labels: internal

#110 Fix: page store tab active listener
  reporting/src/webrequest-pipeline/page-store.js
Labels: bug, patch
